# Python Basics

## 1. Python Variables

1.1 Assign the values “Max” and “Mustermann” to the variables “name” and “lastname” respectively.
Print out the full name and let the printed text beginn with “My name is” but do this part not assign to
a variable.

In [2]:
name = 'Max'
lastname = 'Mustermann'

print('My name is ' + name + " " +  lastname)

My name is Max Mustermann


1.2 Display the result of “14*5-9” math expression using the variables x,y, and z

In [3]:
x = 14
y = 5
z = 9

print(x*y-z)

61


## 2. Python Strings

2.1 Given the following string:
text="Python is a programming language"
a) Add a second sentence to the variable text and separate the two sentences with a dot: “It
doesn’t require semicolons”. Print the result
b) Remove the spaces between the words.

In [4]:
text = "Python is a programming language"

text = "Python is a programming language" + ". It doesn't require semicolons"

print(text)

Python is a programming language. It doesn't require semicolons


In [6]:
text_no_spaces = text.replace(" ", "")

print(text_no_spaces)

Pythonisaprogramminglanguage.Itdoesn'trequiresemicolons


2.2 Combine all of the variables below into the following string “I bought 2 black t-shirts for 10 euro”,
using format() method and String Concatenation. Print it.

In [9]:
item = "t-shirt"
price = 10
amount = 2
color = "black"
currency ="euro"

txt = 'I bought {} {} {}s for {} {}'.format(amount, color, item, price, currency)
print(txt)

I bought 2 black t-shirts for 10 euro


2.3 Split the following string into a list, where each word is a list item. Print it.

In [12]:
text = "This is a string exercise"

split_sentence = text2.split(' ')
print(split_sentence)


['This', 'is', 'a', 'string', 'exercise']


2.4 Replace the first two occurrences of word "cow" with the word "chicken". Print the result

In [14]:
farm = "The farmer has 2 black cows, 3 white cows, 2 brown cows, 4 pigs and 5 horses"
farm = farm.replace("cow", "chicken", 2)
print(farm)

The farmer has 2 black chickens, 3 white chickens, 2 brown cows, 4 pigs and 5 horses


## 3. Python Lists, Sets, Tuples, Dictionaries

3.1 With a list given:
ShoppingList = ["yoghurt", "milk", "eggs"]
a) Change “yoghurt” to “pudding”
b) Add “juice” before “eggs”
Print the resulting list

In [18]:
ShoppingList = ["yoghurt", "milk", "eggs"]

ShoppingList[0] = "pudding"

ShoppingList.insert(2, "juice")

print(ShoppingList)

['pudding', 'milk', 'juice', 'eggs']


3.2 The following set is given. Remove the invalid item (skating) from the set and print it:
SportsWithBall = {"baseball", "skating", "tennis", "football"}

In [19]:
SportsWithBall = {"baseball", "skating", "tennis", "football"}

SportsWithBall.remove("skating")

print(SportsWithBall)

{'football', 'baseball', 'tennis'}


3.3 The following tuple is given
animals = ("cat", "duck", "chicken", "turtle")
a) Unpack the tuple by animal type: mammal, bird, reptile
b) Add "pigeon" to the tuple
c) Remove "chicken" from the tuple
Print it each time.

In [21]:
animals = ("cat", "duck", "chicken", "turtle")

(mammal, *bird, reptile) = animals
print(mammal)
print(bird)
print(reptile)

cat
['duck', 'chicken']
turtle


Da tuple nicht editierbar sind und keine Append oder Remove funktion haben muss ein Workaroud verwendet werden. ZUm hinzufügen wird zuächst das Tier auch als Tuple gespeichert und danach hinzugefügt.

In [22]:
add = ("pigeon",)
animals += add

print(animals)

('cat', 'duck', 'chicken', 'turtle', 'pigeon')


Für das Löschen eines Elementes wird ein anderes Workaround verwendet. Zunächst wird das Tupel einer Variable zugeordnet und dann in eine Liste umegewandelt, das item wird gelöscht und danach wird die Liste wieder in ein Tupel umgewandelt und wieder animals zugewiesen.

In [ ]:
y = list(animals)
y.remove("chicken")
animals = tuple(y)

3.4 Create a dictionary, that contains following data and print it:
Name of job: Barista
Job type: Part-time
Hours per week: 20
Duties: coffee, desserts

In [23]:
dict = {
    "Name of job" : "Barista",
    "Job type" : "Part-time",
    "Hours per week" : 20,
    "Duties" : "coffee, desserts"
}
print(dict)

{'Name of job': 'Barista', 'Job type': 'Part-time', 'Hours per week': 20, 'Duties': 'coffee, desserts'}


3.5 There are four students sharing together an apartment.
a) Create the nested dictionary “roommates”, containing this data:
Name, age, major of each roommate.
• Alice, 25, physics
• Bob, 20, management
• Eve, 23, linguistics
• Mallory, 19, computer science
b) Add a new person to the household (Trent, 29, literature)

In [25]:
roommates = {
    "roommate1" : {
        "name" : "Alice",
        "age": 25,
        "major" : "physics"
    },
    "roommate2": {
        "name" : "Bob",
        "age": 20,
        "major" : "management"
    },
    "roommate3": {
        "name" : "Mallory",
        "age": 19,
        "major" : "computer science"
    }
}

roommates["roommate4"] = {
        "name" : "Trent",
        "age": 29,
        "major" : "literature"
}

print(roommates)

{'roommate1': {'name': 'Alice', 'age': 25, 'major': 'physics'}, 'roommate2': {'name': 'Bob', 'age': 20, 'major': 'management'}, 'roommate3': {'name': 'Mallory', 'age': 19, 'major': 'computer science'}, 'roommate4': {'name': 'Trent', 'age': 29, 'major': 'literature'}}


## Python NumPy

4.1 Perform the following tasks:
a) Create a 3d array arr3D which consists of three 2D-Arrays, that contain 2 arrays with values 1,2
and 3,4.
b) Print out the first element of the second array which is stored in the third array.

In [35]:
import numpy as np

arr3D = np.array([[[1,2],[3,4]],[[1,2],[3,4]],[[1,2],[3,4]]])

print(arr3D[2][1][0])

3


4.2 With 1D-Array given:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,13,14,15,16])
change the shape of the array from 1-D to 3-D. Print the result

In [43]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,13,14,15,16])

newarr = arr.reshape(4,2,2)
print(newarr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
3


## 5. Python Pandas

5.1 Create a DataFrame from the "roommates" dictionary (see 3.5). Print out the DataFrame.

In [48]:
import pandas as pd

df = pd.DataFrame(roommates)
df = df.transpose()
print(df)

              name age             major
roommate1    Alice  25           physics
roommate2      Bob  20        management
roommate3  Mallory  19  computer science
roommate4    Trent  29        literature


5.2 Import the DataFrame from the sheet "Students" (students.xlsx) and print the last 10 rows.

In [50]:
students = pd.read_excel("01_Assignment_PythonBasics_students.xlsx")
print(students.head(10))

          name     land  year
0   univesity1  Germany  1974
1   univesity2    Italy  1980
2   univesity3  Germany  1970
3   univesity4   France  1971
4   univesity5      USA  1861
5   univesity6  Germany  1386
6   univesity7  England  1209
7   univesity8    Spain  1886
8   univesity9   France  1530
9  univesity10   Canada  1910


In [ ]:
5.3 Import the students.csv file using Pandas and print out the DataFrame.

In [52]:
students2 = pd.read_csv("01_Assignment_PythonBasics_students.csv", sep = ";")
print(students2)

      name     sex  age                         major
0    name1  female   20              computer science
1    name2    male   20                     marketing
2    name3    male   19                     economics
3    name4  female   25                   linguistics
4    name5  female   22                    literature
5    name6    male   21         software engineering 
6    name7    male   30              computer science
7    name8  female   24              computer science
8    name9    male   20             political science
9   name10  female   23                    management
10  name11  female   21                    philosophy
11  name13  female   22                     economics
12  name13    male   26                       physics
13  name14  female   20                     chemistry
14  name15    male   25                      medicine
15  name16  female   19  english and american studies
16  name17  female   22                     geography
17  name18    male   19     