# Python Basics

## 1. Python Variables

1.1 Assign the values “Max” and “Mustermann” to the variables “name” and “lastname” respectively.
Print out the full name and let the printed text beginn with “My name is” but do this part not assign to
a variable.

In [1]:
name = 'Max'
lastname = 'Mustermann'

print('My name is ' + name + " " +  lastname)

My name is Max Mustermann


1.2 Display the result of “14*5-9” math expression using the variables x,y, and z

In [2]:
x = 14
y = 5
z = 9

print(x*y-z)

61


## 2. Python Strings

2.1 Given the following string:
text="Python is a programming language"
a) Add a second sentence to the variable text and separate the two sentences with a dot: “It
doesn’t require semicolons”. Print the result
b) Remove the spaces between the words.

In [3]:
text = "Python is a programming language"

text = "Python is a programming language" + ". It doesn't require semicolons"

print(text)

Python is a programming language. It doesn't require semicolons


In [4]:
text_no_spaces = text.replace(" ", "")

print(text_no_spaces)

Pythonisaprogramminglanguage.Itdoesn'trequiresemicolons


2.2 Combine all of the variables below into the following string “I bought 2 black t-shirts for 10 euro”,
using format() method and String Concatenation. Print it.

Dafür werden zunächst für die Einzusetzenden Werte Variablen erstellt und der entsprechende Wert zugewiesen. Und danach durch die .format() Funktion zu einem Satz zusammengefügt.

In [5]:
item = "t-shirt"
price = 10
amount = 2
color = "black"
currency ="euro"

txt = 'I bought {} {} {}s for {} {}'.format(amount, color, item, price, currency)
print(txt)

I bought 2 black t-shirts for 10 euro


2.3 Split the following string into a list, where each word is a list item. Print it.

Dafür wird die Funktion split() verwendet und in dieser das Leerzeichen als Trennzeichen angegeben.

In [7]:
text2 = "This is a string exercise"

split_sentence = text2.split(' ')
print(split_sentence)


['This', 'is', 'a', 'string', 'exercise']


2.4 Replace the first two occurrences of word "cow" with the word "chicken". Print the result

Hierfür wird die replace Funktion verwendet und hier zunächst das zu ersetzende Wort angegeben und danach das neue und zuletzt noch die Anzahl die Ersetzt werden soll.

In [8]:
farm = "The farmer has 2 black cows, 3 white cows, 2 brown cows, 4 pigs and 5 horses"
farm = farm.replace("cow", "chicken", 2)
print(farm)

The farmer has 2 black chickens, 3 white chickens, 2 brown cows, 4 pigs and 5 horses


## 3. Python Lists, Sets, Tuples, Dictionaries

3.1 With a list given: </br>
ShoppingList = ["yoghurt", "milk", "eggs"] </br>
a) Change “yoghurt” to “pudding” </br>
b) Add “juice” before “eggs” </br>
Print the resulting list </br>

Dafür wird zunächste die Shopping Liste erstellt und dann an die 0 Stelle in der yogurt steht dieser Wert mit Pudding ersetzt. Da wir genau wissen wo yoghurt steht können wir die direkte postion verwenden. Um Juice vor Eggs hinzuzufügen verwenden wir die insert Funktion und geben die Stelle hinter der eingesetzt und den Wert an.

In [9]:
ShoppingList = ["yoghurt", "milk", "eggs"]

ShoppingList[0] = "pudding"

ShoppingList.insert(2, "juice")

print(ShoppingList)

['pudding', 'milk', 'juice', 'eggs']


3.2 The following set is given. Remove the invalid item (skating) from the set and print it:
SportsWithBall = {"baseball", "skating", "tennis", "football"} 

Um dies zu tun wird die remove Funktion verwender und das entfernende Element aus dem Set angegeben.

In [10]:
SportsWithBall = {"baseball", "skating", "tennis", "football"}

SportsWithBall.remove("skating")

print(SportsWithBall)

{'football', 'baseball', 'tennis'}


3.3 The following tuple is given </br>
animals = ("cat", "duck", "chicken", "turtle") </br>
a) Unpack the tuple by animal type: mammal, bird, reptile </br>
b) Add "pigeon" to the tuple </br>
c) Remove "chicken" from the tuple </br>
Print it each time. </br>

Dafür wird das Tupel unpacked und die entsprechenden Bezeichnungen zugewiesen, bei bird mit * da es zwei nacheinander sind. ZUletzt werden sie ausgegeben.

In [11]:
animals = ("cat", "duck", "chicken", "turtle")

(mammal, *bird, reptile) = animals
print(mammal)
print(bird)
print(reptile)

cat
['duck', 'chicken']
turtle


Da tuple nicht editierbar sind und keine Append oder Remove funktion haben muss ein Workaroud verwendet werden. ZUm hinzufügen wird zuächst das Tier auch als Tuple gespeichert und danach hinzugefügt.

In [12]:
add = ("pigeon",)
animals += add

print(animals)

('cat', 'duck', 'chicken', 'turtle', 'pigeon')


Für das Löschen eines Elementes wird ein anderes Workaround verwendet. Zunächst wird das Tupel einer Variable zugeordnet und dann in eine Liste umegewandelt, das item wird gelöscht und danach wird die Liste wieder in ein Tupel umgewandelt und wieder animals zugewiesen.

In [13]:
y = list(animals)
y.remove("chicken")
animals = tuple(y)

3.4 Create a dictionary, that contains following data and print it: </br>
Name of job: Barista </br>
Job type: Part-time </br>
Hours per week: 20 </br>
Duties: coffee, desserts </br>


In [14]:
dict = {
    "Name of job" : "Barista",
    "Job type" : "Part-time",
    "Hours per week" : 20,
    "Duties" : "coffee, desserts"
}
print(dict)

{'Name of job': 'Barista', 'Job type': 'Part-time', 'Hours per week': 20, 'Duties': 'coffee, desserts'}


3.5 There are four students sharing together an apartment. </br>
a) Create the nested dictionary “roommates”, containing this data:  </br>
Name, age, major of each roommate. </br>
• Alice, 25, physics </br>
• Bob, 20, management </br>
• Eve, 23, linguistics </br> 
• Mallory, 19, computer science </br>
b) Add a new person to the household (Trent, 29, literature) </br>

Um eine neue Person hinzuzufügen muss die Bezeichnung dieser angegeben werden und dann alle Elemente die auch die anderen Dictionary einträge haben.

In [15]:
roommates = {
    "roommate1" : {
        "name" : "Alice",
        "age": 25,
        "major" : "physics"
    },
    "roommate2": {
        "name" : "Bob",
        "age": 20,
        "major" : "management"
    },
    "roommate3": {
        "name" : "Mallory",
        "age": 19,
        "major" : "computer science"
    }
}

roommates["roommate4"] = {
        "name" : "Trent",
        "age": 29,
        "major" : "literature"
}

print(roommates)

{'roommate1': {'name': 'Alice', 'age': 25, 'major': 'physics'}, 'roommate2': {'name': 'Bob', 'age': 20, 'major': 'management'}, 'roommate3': {'name': 'Mallory', 'age': 19, 'major': 'computer science'}, 'roommate4': {'name': 'Trent', 'age': 29, 'major': 'literature'}}


## Python NumPy

4.1 Perform the following tasks:
a) Create a 3d array arr3D which consists of three 2D-Arrays, that contain 2 arrays with values 1,2
and 3,4.
b) Print out the first element of the second array which is stored in the third array.

In [16]:
import numpy as np

arr3D = np.array([[[1,2],[3,4]],[[1,2],[3,4]],[[1,2],[3,4]]])

print(arr3D[2][1][0])

3


4.2 With 1D-Array given:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,13,14,15,16]) </br>
change the shape of the array from 1-D to 3-D. Print the result </br>

Um die Form zu ändern wird die Funktion reshape verwendet.

In [17]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,13,14,15,16])

newarr = arr.reshape(4,2,2)
print(newarr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]


## 5. Python Pandas

5.1 Create a DataFrame from the "roommates" dictionary (see 3.5). Print out the DataFrame.

Um aus den Dictionary einen DataFrame zu machen wird die Pandas Funktion pd.DataFrame verwendet. Danach noch die transpose funktion damit der DataFrame übersichtlich dargestellt werden kann.

In [18]:
import pandas as pd

df = pd.DataFrame(roommates)
df = df.transpose()
print(df)

              name age             major
roommate1    Alice  25           physics
roommate2      Bob  20        management
roommate3  Mallory  19  computer science
roommate4    Trent  29        literature


5.2 Import the DataFrame from the sheet "Students" (students.xlsx) and print the last 10 rows.

Zum importieren wird die pd.read_excel Funtkion verwendet und zum Ausgeben von den letzten 10 Reihen, die tail Funktion mit dem Input 10.

In [22]:
students = pd.read_excel("01_Assignment_PythonBasics_students.xlsx")
print(students.tail(10))

           name         land  year
15  univesity16      England  1977
16  univesity17      Austria  1622
17  univesity18      Germany  1966
18  univesity19      Germany  1825
19  univesity20        Spain  1608
20  univesity21  Netherlands  1575
21  univesity22      Austria  1669
22  univesity23       Poland  1816
23  univesity24      England  1832
24  univesity25      Germany  1962


5.3 Import the students.csv file using Pandas and print out the DataFrame.

Um die csv Datei zu importieren wird die pd.read_csv Funktion verwendet un der Spereator angegeben.

In [21]:
students2 = pd.read_csv("01_Assignment_PythonBasics_students.csv", sep = ";")
print(students2)

      name     sex  age                         major
0    name1  female   20              computer science
1    name2    male   20                     marketing
2    name3    male   19                     economics
3    name4  female   25                   linguistics
4    name5  female   22                    literature
5    name6    male   21         software engineering 
6    name7    male   30              computer science
7    name8  female   24              computer science
8    name9    male   20             political science
9   name10  female   23                    management
10  name11  female   21                    philosophy
11  name13  female   22                     economics
12  name13    male   26                       physics
13  name14  female   20                     chemistry
14  name15    male   25                      medicine
15  name16  female   19  english and american studies
16  name17  female   22                     geography
17  name18    male   19     